apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 10.71.243.51
        - name: WORDPRESS_DB_PASSWORD
          value: admin
        - name: WORDPRESS_DB_USER
          value: admin
        - name: WORDPRESS_DB_NAME
          value: mydb
        - name: WORDPRESS_DEBUG
          value: “1”
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
        volumes:
        - name: wordpress-pv
          persistentVolumeClaim:
            claimName: wordpress-pvc